### ISSUE TITLE
Komentář k pracantovi

### ISSUE THREAD

**Issue by jilekmarek** [ladal1/summerjob#13]
Prosím o přídání možnosti nahrát/editovat interní komentář k pracantovi, který bude viditelný pouze pro tým a který bude možné zobrazit pouze po kliku na uživatele.

Bude sloužit pro komentáře typu: zaplatil, umí malovat, DT

Dík! ;)

**Comment by LGAP98** [comment]
Už je hotovo :D

**Comment by jilekmarek** [comment]
Super, díky ;)
![obrazek](https://github.com/ladal1/summerjob/assets/13977093/cef59a93-6cee-4090-85e0-dce6b7e0b053)
